# Generated by Django 3.2.3 on 2021-06-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('EstimatedMonths', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('transactionMethod', models.CharField(choices=[('Bank Transfer', 'Bt'), ('Paypal', 'Paypal'), ('Payoneer', 'Payoneer'), ('Western Union', 'Wu'), ('RIA', 'Ria'), ('Moneygram', 'Mg')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('transactionMethod', models.CharField(choices=[('Bank Transfer', 'Bt'), ('Paypal', 'Paypal'), ('Payoneer', 'Payoneer'), ('Western Union', 'Wu'), ('RIA', 'Ria'), ('Moneygram', 'Mg')], max_length=20)),
                ('is_Graduate', models.BooleanField(default=False)),
                ('is_Master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsappGroupLink', models.IntegerField(blank=True, null=True)),
                ('zoomLink', models.IntegerField(blank=True, null=True)),
                ('monthlyFees', models.IntegerField(default=0)),
                ('joiningDate', models.DateField()),
                ('hoursPerMonth', models.IntegerField()),
                ('sessionsPerMonth', models.IntegerField()),
                ('time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.teacher')),
            ],
        ),
    ]
