# Generated by Django 3.2.4 on 2021-06-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('experiencedYears', models.IntegerField(blank=True, null=True)),
                ('expectedSalary', models.IntegerField()),
                ('preferredCurrency', models.CharField(max_length=10)),
                ('intro', models.CharField(max_length=300)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('estimatedMonths', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('transactionMethod', models.CharField(choices=[('Bank Transfer', 'Bt'), ('Paypal', 'Paypal'), ('Payoneer', 'Payoneer'), ('Western Union', 'Wu'), ('RIA', 'Ria'), ('Moneygram', 'Mg')], max_length=20)),
                ('speaks_english', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('experiencedYears', models.IntegerField(blank=True, null=True)),
                ('intro', models.CharField(max_length=300)),
                ('is_trainee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('whatsappGroupLink', models.CharField(blank=True, max_length=50, null=True)),
                ('zoomLink', models.CharField(blank=True, max_length=50, null=True)),
                ('monthlyDebit', models.IntegerField(default=0)),
                ('monthlyCredit', models.IntegerField(default=0)),
                ('joiningDate', models.DateField()),
                ('hoursPerMonth', models.IntegerField()),
                ('sessionsPerMonth', models.IntegerField()),
                ('time', models.TimeField()),
                ('language', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=200)),
                ('is_training', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.teacher')),
            ],
        ),
    ]
