# Generated by Django 3.2.3 on 2021-06-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('transactionMethod', models.CharField(choices=[('Bank Transfer', 'Bt'), ('Paypal', 'Paypal'), ('Payoneer', 'Payoneer'), ('Western Union', 'Wu'), ('RIA', 'Ria'), ('Moneygram', 'Mg')], max_length=20)),
                ('is_graduate', models.BooleanField(default=False)),
                ('is_master', models.BooleanField(default=False)),
                ('experiencedYears', models.IntegerField(blank=True, null=True)),
                ('speaks_english', models.BooleanField()),
                ('has_interviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='EstimatedMonths',
            new_name='estimatedMonths',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='is_Graduate',
            new_name='is_graduate',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='is_Master',
            new_name='is_master',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.CharField(default='English', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='title',
            field=models.CharField(default="Ahmed's programming classroom with Ammar", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='speaks_english',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='experiencedYears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='speaks_english',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
