# Generated by Django 3.2.3 on 2021-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210604_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='has_interviewed',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_graduate',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='speaks_english',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='transactionMethod',
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='expectedSalary',
            field=models.IntegerField(default=25000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='intro',
            field=models.CharField(default='abc', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferredCurrency',
            field=models.CharField(default='abc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='abc', upload_to=''),
            preserve_default=False,
        ),
    ]
