# Generated by Django 3.2.4 on 2021-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20210607_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='monthlyFees',
            new_name='monthlyCredit',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='joiningDate',
            new_name='startingDate',
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='monthlyDebit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_trainee',
            field=models.BooleanField(default=False),
        ),
    ]
