# Generated by Django 3.2.3 on 2021-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20210607_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='joiningDate',
            new_name='startingDate',
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.CharField(default='m,t,w', max_length=30),
            preserve_default=False,
        ),
    ]
