# Generated by Django 3.2.4 on 2021-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20210607_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='whatsappGroupLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
