# Generated by Django 3.2.4 on 2021-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_alter_class_whatsappgrouplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='zoomLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
